### ISSUE TITLE
builtins.ImportError: No module named 'crossbar.adapter.postgres'

### ISSUE THREAD

**Issue by Belanchuk** [crossbario/crossbar-examples#106]
~/crossbar-examples/database/postgresql/publisher % crossbar start
> 2017-10-27T14:42:20+0500 [Controller  25105] File permissions on node public key fixed!
2017-10-27T14:42:20+0500 [Controller  25105] File permissions on node private key fixed!
2017-10-27T14:42:20+0500 [Controller  25105]      __  __  __  __  __  __      __     __
2017-10-27T14:42:20+0500 [Controller  25105]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2017-10-27T14:42:20+0500 [Controller  25105]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2017-10-27T14:42:20+0500 [Controller  25105]                                         
2017-10-27T14:42:20+0500 [Controller  25105] Version:     Crossbar.io COMMUNITY 17.9.2
2017-10-27T14:42:20+0500 [Controller  25105] Public Key:  8d356eb4c224354335f28b6e9f8b9cf2a58059b6ced1b88a4ce3b06836faabae
2017-10-27T14:42:20+0500 [Controller  25105] 
2017-10-27T14:42:20+0500 [Controller  25105] Node starting with personality "community" [crossbar.controller.node.Node]
2017-10-27T14:42:20+0500 [Controller  25105] Running from node directory "\~/crossbar-examples/database/postgresql/publisher/.crossbar"
2017-10-27T14:42:20+0500 [Controller  25105] Node configuration loaded from "\~/crossbar-examples/database/postgresql/publisher/.crossbar/config.json"
2017-10-27T14:42:20+0500 [Controller  25105] Controller process starting [CPython-EPollReactor] ..
2017-10-27T14:42:20+0500 [Controller  25105] No extra node router roles
2017-10-27T14:42:20+0500 [Controller  25105] RouterServiceSession ready [no on_ready configured]
2017-10-27T14:42:20+0500 [Controller  25105] Registered 20 procedures
2017-10-27T14:42:20+0500 [Controller  25105] Using default node shutdown triggers ['shutdown_on_worker_exit']
2017-10-27T14:42:20+0500 [Controller  25105] Configuring node from local configuration ...
2017-10-27T14:42:20+0500 [Controller  25105] Starting 1 workers ...
2017-10-27T14:42:20+0500 [Controller  25105] Router worker "worker-001" starting ..
2017-10-27T14:42:21+0500 [Router      25111] Started Router worker "worker-001" [crossbar.worker.router.RouterWorkerSession / CPython-EPollReactor]
2017-10-27T14:42:21+0500 [Router      25111] Router worker "worker-001" session 1511840525022489 initializing ..
2017-10-27T14:42:21+0500 [Router      25111] Registered 35 procedures
2017-10-27T14:42:21+0500 [Router      25111] Router worker "worker-001" session ready
2017-10-27T14:42:21+0500 [Controller  25105] Router worker "worker-001" process 25111 started
2017-10-27T14:42:21+0500 [Router      25111] RouterServiceSession ready [configured on_ready fired]
2017-10-27T14:42:21+0500 [Router      25111] Realm 'realm1' started
2017-10-27T14:42:21+0500 [Controller  25105] Router "worker-001": realm 'realm-001' (named 'realm1') started
2017-10-27T14:42:21+0500 [Router      25111] role role-001 on realm realm-001 started
2017-10-27T14:42:21+0500 [Controller  25105] Router "worker-001": role 'role-001' (named 'anonymous') started on realm 'realm-001'
2017-10-27T14:42:21+0500 [Router      25111] ApplicationError: ApplicationError(error=<crossbar.error.class_import_failed>, args=['Failed to import class \'crossbar.adapter.postgres.PostgreSQLPublisher\'\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/autobahn-17.9.3-py3.5.egg/autobahn/wamp/protocol.py", line 895, in onMessage\n    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)\n  File "/usr/local/lib/python3.5/dist-packages/txaio/tx.py", line 417, in as_future\n    return maybeDeferred(fun, *args, **kwargs)\n  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File "/usr/local/lib/python3.5/dist-packages/crossbar/worker/router.py", line 1287, in start_router_component\n    create_component = _appsession_loader(config)\n--- <exception caught here> ---\n  File "/usr/local/lib/python3.5/dist-packages/crossbar/worker/__init__.py", line 58, in _appsession_loader\n    module = importlib.import_module(module_name)\n  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 986, in _gcd_import\n    \n  File "<frozen importlib._bootstrap>", line 969, in _find_and_load\n    \n  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked\n    \nbuiltins.ImportError: No module named \'crossbar.adapter.postgres\'\n'], kwargs={'pythonpath': ['', '/usr/local/bin', '/usr/local/lib/python3.5/dist-packages/autobahn-17.9.3-py3.5.egg', '/usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg', '/usr/local/lib/python3.5/dist-packages/pyasn1-0.3.7-py3.5.egg', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/home/gf/.local/lib/python3.5/site-packages', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']}, enc_algo=None): Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/autobahn-17.9.3-py3.5.egg/autobahn/twisted/websocket.py", line 162, in _onMessage
    self.onMessage(payload, isBinary)
  File "/usr/local/lib/python3.5/dist-packages/autobahn-17.9.3-py3.5.egg/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/usr/local/lib/python3.5/dist-packages/autobahn-17.9.3-py3.5.egg/autobahn/wamp/protocol.py", line 895, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/txaio/tx.py", line 417, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/crossbar/worker/router.py", line 1287, in start_router_component
    create_component = _appsession_loader(config)
  File "/usr/local/lib/python3.5/dist-packages/crossbar/worker/__init__.py", line 74, in _appsession_loader
    pythonpath=sys.path
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.class_import_failed>, args=['Failed to import class \'crossbar.adapter.postgres.PostgreSQLPublisher\'\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/autobahn-17.9.3-py3.5.egg/autobahn/wamp/protocol.py", line 895, in onMessage\n    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)\n  File "/usr/local/lib/python3.5/dist-packages/txaio/tx.py", line 417, in as_future\n    return maybeDeferred(fun, *args, **kwargs)\n  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File "/usr/local/lib/python3.5/dist-packages/crossbar/worker/router.py", line 1287, in start_router_component\n    create_component = _appsession_loader(config)\n--- <exception caught here> ---\n  File "/usr/local/lib/python3.5/dist-packages/crossbar/worker/__init__.py", line 58, in _appsession_loader\n    module = importlib.import_module(module_name)\n  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 986, in _gcd_import\n    \n  File "<frozen importlib._bootstrap>", line 969, in _find_and_load\n    \n  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked\n    \nbuiltins.ImportError: No module named \'crossbar.adapter.postgres\'\n'], kwargs={'pythonpath': ['', '/usr/local/bin', '/usr/local/lib/python3.5/dist-packages/autobahn-17.9.3-py3.5.egg', '/usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg', '/usr/local/lib/python3.5/dist-packages/pyasn1-0.3.7-py3.5.egg', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '\~/.local/lib/python3.5/site-packages', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']}, enc_algo=None)
2017-10-27T14:42:21+0500 [Controller  25105] crossbar.error.class_import_failed: Failed to import class 'crossbar.adapter.postgres.PostgreSQLPublisher'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/autobahn-17.9.3-py3.5.egg/autobahn/wamp/protocol.py", line 895, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/txaio/tx.py", line 417, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/crossbar/worker/router.py", line 1287, in start_router_component
    create_component = _appsession_loader(config)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/crossbar/worker/__init__.py", line 58, in _appsession_loader
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
builtins.ImportError: No module named 'crossbar.adapter.postgres'
2017-10-27T14:42:21+0500 [Controller  25105] sending TERM to subprocess 25111
2017-10-27T14:42:21+0500 [Controller  25105] waiting for 25111 to exit...
2017-10-27T14:42:21+0500 [Router      25111] Native worker received SIGTERM - shutting down ..
2017-10-27T14:42:21+0500 [Router      25111] Shutdown of worker requested!
2017-10-27T14:42:21+0500 [Router      25111] Connection to node controller closed cleanly
2017-10-27T14:42:21+0500 [Controller  25105] Native worker connection closed cleanly.
2017-10-27T14:42:21+0500 [Controller  25105] Node worker worker-001 ended successfully
2017-10-27T14:42:21+0500 [Controller  25105] Checking for node shutdown: worker_exit_success=True, shutdown_requested=False, node_shutdown_triggers=['shutdown_on_worker_exit']
2017-10-27T14:42:21+0500 [Controller  25105] Node worker ended, and trigger 'shutdown_on_worker_exit' active
2017-10-27T14:42:21+0500 [Controller  25105] Node shutdown requested ..

**Comment by Belanchuk** [comment]
~/crossbar-examples/database/postgresql/publisher % crossbar version
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 17.9.2 (Crossbar.io COMMUNITY)
   Autobahn         : 17.9.3 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 17.9.0-EPollReactor
   LMDB             : 0.93/lmdb-0.9.18
   Python           : 3.5.2/CPython
 OS                 : Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial
 Machine            : x86_64
 Release key        : RWRj+Sb8UH/pwLCycZ+3OroR5UV9aaLUDVbKxNcj+gYoOOZv0LrzMH1a

**Comment by Belanchuk** [comment]
~/crossbar-examples/database/postgresql/publisher % which crossbar
/usr/local/bin/crossbar

**Comment by Belanchuk** [comment]
I found the crossbar.adapter.postgres in https://github.com/crossbario/crossbar/tree/v0.13.0/crossbar/adapter/postgres
https://github.com/crossbario/crossbar/commit/07e9a831b13070abb56e5f52f3a8ca76371db73b?diff=unified

It would be interesting to know why it was deleted.
