### ISSUE TITLE
Getting error trying to run publisher example.

### ISSUE THREAD

**Issue by Alexeyisme** [crossbario/crossbar-examples#113]
Hi! 

Ubuntu 18.04, virtualenv, Python 3.6.6.

I ran `/crossbar-examples/rest/publisher$ crossbar start`
And got an error `builtins.ValueError: 192.168.1.1/24 has host bits set`

Logs:
```

2018-10-02T19:00:34+0400 [Controller   9138] 
2018-10-02T19:00:34+0400 [Controller   9138]     :::::::::::::::::
2018-10-02T19:00:34+0400 [Controller   9138]           :::::          _____                      __
2018-10-02T19:00:34+0400 [Controller   9138]     :::::   :   :::::   / ___/____ ___   ___  ___  / /  ___ _ ____
2018-10-02T19:00:34+0400 [Controller   9138]     :::::::   :::::::  / /__ / __// _ \ (_-< (_-< / _ \/ _ `// __/
2018-10-02T19:00:34+0400 [Controller   9138]     :::::   :   :::::  \___//_/   \___//___//___//_.__/\_,_//_/
2018-10-02T19:00:34+0400 [Controller   9138]           :::::
2018-10-02T19:00:34+0400 [Controller   9138]     :::::::::::::::::   Crossbar v18.9.2
2018-10-02T19:00:34+0400 [Controller   9138] 
2018-10-02T19:00:34+0400 [Controller   9138]     Copyright (c) 2013-2018 Crossbar.io Technologies GmbH, licensed under AGPL 3.0.
2018-10-02T19:00:34+0400 [Controller   9138] 
2018-10-02T19:00:34+0400 [Controller   9138] Initializing <class 'crossbar.personality.Personality'> node from node directory "/home/alexeyisme/Development/My_learning_projects/Crossbar/crossbar-examples/rest/publisher/.crossbar" 
2018-10-02T19:00:34+0400 [Controller   9138] Node key loaded from "/home/alexeyisme/Development/My_learning_projects/Crossbar/crossbar-examples/rest/publisher/.crossbar/key.priv"
2018-10-02T19:00:34+0400 [Controller   9138] Node configuration loaded from "/home/alexeyisme/Development/My_learning_projects/Crossbar/crossbar-examples/rest/publisher/.crossbar/config.json"
2018-10-02T19:00:34+0400 [Controller   9138] Entering event reactor ...
2018-10-02T19:00:34+0400 [Controller   9138] Starting standalone node 
2018-10-02T19:00:34+0400 [Controller   9138] Node ID "alexeyisme-lenovo-g500" set from hostname
2018-10-02T19:00:34+0400 [Controller   9138] No extra node router roles
2018-10-02T19:00:34+0400 [Controller   9138] RouterServiceAgent ready (realm_name="crossbar", on_ready=None)
2018-10-02T19:00:34+0400 [Controller   9138] Registered 21 procedures
2018-10-02T19:00:34+0400 [Controller   9138] Signal handler installed on process 9138 thread 140462934198080
2018-10-02T19:00:34+0400 [Controller   9138] Using default node shutdown triggers ['shutdown_on_worker_exit']
2018-10-02T19:00:34+0400 [Controller   9138] Booting node 
2018-10-02T19:00:34+0400 [Controller   9138] Configuring node from local configuration 
2018-10-02T19:00:34+0400 [Controller   9138] Starting 1 workers ...
2018-10-02T19:00:34+0400 [Controller   9138] Starting router worker "worker-001" 
2018-10-02T19:00:34+0400 [Controller   9138] Starting new managed worker process for Router worker "worker-001"
2018-10-02T19:00:35+0400 [Router       9144] Starting worker "worker-001" for node "alexeyisme-lenovo-g500" with personality "standalone" 
2018-10-02T19:00:35+0400 [Router       9144] Running as PID 9144 on CPython-EPollReactor
2018-10-02T19:00:35+0400 [Router       9144] Entering event reactor ...
2018-10-02T19:00:35+0400 [Router       9144] Router worker session for "worker-001" joined realm "crossbar" on node router 
2018-10-02T19:00:35+0400 [Router       9144] Registered 41 procedures
2018-10-02T19:00:35+0400 [Router       9144] Router worker session for "worker-001" ready
2018-10-02T19:00:35+0400 [Controller   9138] Router worker "worker-001" process 9144 started
2018-10-02T19:00:35+0400 [Router       9144] Starting router realm "realm-001" 
2018-10-02T19:00:35+0400 [Router       9144] RouterServiceAgent ready (realm_name="realm1", on_ready=<Deferred at 0x7f11f5e9c8d0>)
2018-10-02T19:00:35+0400 [Router       9144] Realm "realm-001" (name="realm1") started
2018-10-02T19:00:35+0400 [Controller   9138] Router "worker-001": realm 'realm-001' (named 'realm1') started
2018-10-02T19:00:35+0400 [Router       9144] Starting role "role-001" on realm "realm-001" 
2018-10-02T19:00:35+0400 [Router       9144] role role-001 on realm realm-001 started
2018-10-02T19:00:35+0400 [Controller   9138] Router "worker-001": role 'role-001' (named 'anonymous') started on realm 'realm-001'
2018-10-02T19:00:35+0400 [Router       9144] Starting router transport "transport-001" 
2018-10-02T19:00:35+0400 [Router       9144] Creating router transport for "transport-001" 
2018-10-02T19:00:35+0400 [Router       9144] Router transport created for "transport-001" 
2018-10-02T19:00:35+0400 [Router       9144] Site starting on 8080
2018-10-02T19:00:35+0400 [Controller   9138] Router "worker-001": transport 'transport-001' started
2018-10-02T19:00:35+0400 [Router       9144] Starting "publisher" Web service on path "publish" of transport "transport-001" 
2018-10-02T19:00:35+0400 [Controller   9138] Router "worker-001": web service 'publisher' started on path 'publish' on transport 'transport-001'
2018-10-02T19:00:35+0400 [Router       9144] Starting "publisher" Web service on path "publish-signed" of transport "transport-001" 
2018-10-02T19:00:35+0400 [Router       9144] ValueError: 192.168.1.1/24 has host bits set: Traceback (most recent call last):
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 166, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 936, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/txaio/tx.py", line 429, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/crossbar/worker/router.py", line 842, in start_web_transport_service
    webservice = webservice_factory.create(transport, path, config)
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/crossbar/webservice/rest.py", line 64, in create
    auth_config=config.get('auth', {}))
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/crossbar/bridge/rest/common.py", line 99, in __init__
    self._require_ip = [ip_network(net) for net in options['require_ip']]
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/crossbar/bridge/rest/common.py", line 99, in <listcomp>
    self._require_ip = [ip_network(net) for net in options['require_ip']]
  File "/usr/lib/python3.6/ipaddress.py", line 74, in ip_network
    return IPv4Network(address, strict)
  File "/usr/lib/python3.6/ipaddress.py", line 1519, in __init__
    raise ValueError('%s has host bits set' % self)
builtins.ValueError: 192.168.1.1/24 has host bits set

2018-10-02T19:00:35+0400 [Controller   9138] Could not start node: Traceback (most recent call last):
--- <exception caught here> ---
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/crossbar/node/node.py", line 327, in start
    yield self.personality.Node.boot(self)
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/crossbar/node/node.py", line 406, in boot_from_config
    yield config_fn(worker_logname, worker_id, worker)
  File "/home/alexeyisme/Development/My_learning_projects/Crossbar/env/lib/python3.6/site-packages/crossbar/node/node.py", line 571, in _configure_native_worker_router
    options=CallOptions())
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<wamp.error.runtime_error>, args=['192.168.1.1/24 has host bits set'], kwargs={}, enc_algo=None)

2018-10-02T19:00:35+0400 [Controller   9138] sending TERM to subprocess 9144
2018-10-02T19:00:35+0400 [Controller   9138] waiting for 9144 to exit...
2018-10-02T19:00:35+0400 [Router       9144] Native worker received SIGTERM - shutting down ..
2018-10-02T19:00:35+0400 [Router       9144] Shutdown of worker requested!
2018-10-02T19:00:35+0400 [Router       9144] Connection to node controller closed cleanly
2018-10-02T19:00:35+0400 [Router       9144] (TCP Port 8080 Closed)
2018-10-02T19:00:35+0400 [Controller   9138] Native worker connection closed cleanly.
2018-10-02T19:00:35+0400 [Controller   9138] Node worker worker-001 ended successfully
2018-10-02T19:00:35+0400 [Controller   9138] Checking for node shutdown: worker_exit_success=True, shutdown_requested=False, node_shutdown_triggers=['shutdown_on_worker_exit']
2018-10-02T19:00:35+0400 [Controller   9138] Node worker ended, and trigger 'shutdown_on_worker_exit' is active: will shutdown node ..
2018-10-02T19:00:35+0400 [Controller   9138] Node shutdown requested (restart=False, mode=None, reactor.running=True) ..
```

Is it a bug or my fault?

KR,
Alex

**Comment by oberstet** [comment]
try `192.168.1.0/24`;) note the `0` for "host bits" ..
