### ISSUE TITLE
publisher exemple not working

### ISSUE THREAD

**Issue by codegastudio** [crossbario/crossbar-examples#126]
Hello,

I was trying to send simple publish through http like describe [here](https://crossbar.io/docs/HTTP-Bridge-Publisher/?highlight=crossbarconnect) in my project when i get the following error on crossbar init.

```
Starting "publisher" Web service on path "publish" of transport "transport001" <crossbar.worker.router.RouterController.start_web_transport_service>
 RouterController.onUserError(): "TypeError: add() missing 1 required positional argument: 'router'"
``` 

After many tests on my config.json i try to test [the exemple](https://github.com/crossbario/crossbar-examples/tree/master/rest/publisher) and i get the same error :( 

```
2019-05-23T16:32:35+0200 [Controller  24588] 
2019-05-23T16:32:35+0200 [Controller  24588]     :::::::::::::::::
2019-05-23T16:32:35+0200 [Controller  24588]           :::::          _____                      __
2019-05-23T16:32:35+0200 [Controller  24588]     :::::   :   :::::   / ___/____ ___   ___  ___  / /  ___ _ ____
2019-05-23T16:32:35+0200 [Controller  24588]     :::::::   :::::::  / /__ / __// _ \ (_-< (_-< / _ \/ _ `// __/
2019-05-23T16:32:35+0200 [Controller  24588]     :::::   :   :::::  \___//_/   \___//___//___//_.__/\_,_//_/
2019-05-23T16:32:35+0200 [Controller  24588]           :::::
2019-05-23T16:32:35+0200 [Controller  24588]     :::::::::::::::::   Crossbar v19.5.1
2019-05-23T16:32:35+0200 [Controller  24588] 
2019-05-23T16:32:35+0200 [Controller  24588]     Copyright (c) 2013-2019 Crossbar.io Technologies GmbH, licensed under AGPL 3.0.
2019-05-23T16:32:35+0200 [Controller  24588] 
2019-05-23T16:32:35+0200 [Controller  24588] Initializing <crossbar.node.node.Node> as node [realm=crossbar, cbdir=/applications/enedis/publisher/.crossbar]
2019-05-23T16:32:35+0200 [Controller  24588] New node key pair generated! Public key is 0xd3e509ded813f9608a274cb740784f8d15a181c0b5872252832051b68d0345f1
2019-05-23T16:32:35+0200 [Controller  24588] File permissions on node private key fixed
2019-05-23T16:32:35+0200 [Controller  24588] Node key loaded from /applications/enedis/publisher/.crossbar/key.priv
2019-05-23T16:32:35+0200 [Controller  24588] Node configuration loaded [config_source=localfile, config_path=/applications/enedis/publisher/.crossbar/config.json]
2019-05-23T16:32:35+0200 [Controller  24588] Entering event reactor ...
2019-05-23T16:32:36+0200 [Controller  24588] Starting standalone node <crossbar.node.node.Node.start>
2019-05-23T16:32:36+0200 [Controller  24588] Node ID a2denedis set from hostname
2019-05-23T16:32:36+0200 [Controller  24588] RouterFactory.start_realm: router created for realm "crossbar"
2019-05-23T16:32:36+0200 [Controller  24588] No extra node router roles
2019-05-23T16:32:36+0200 [Controller  24588] Router.attach(session=135532059037188)
2019-05-23T16:32:36+0200 [Controller  24588] Router.attach(session=135532059037188): attached session 135532059037188 to router realm "crossbar"
2019-05-23T16:32:36+0200 [Controller  24588] RouterServiceAgent: realm service session attached (details=SessionDetails(realm=<crossbar>, session=135532059037188, authid=<None>, authrole=<trusted>, authmethod=None, authprovider=None, authextra=None, resumed=None, resumable=None, resume_token=None))
2019-05-23T16:32:36+0200 [Controller  24588] RouterServiceAgent: realm service session ready (realm_name="crossbar", on_ready=None)
2019-05-23T16:32:36+0200 [Controller  24588] Router.attach(session=283968118017875)
2019-05-23T16:32:36+0200 [Controller  24588] Router.attach(session=283968118017875): attached session 283968118017875 to router realm "crossbar"
2019-05-23T16:32:36+0200 [Controller  24588] Registered 23 procedures
2019-05-23T16:32:36+0200 [Controller  24588] Signal handler installed on process 24588 thread 547964788752
2019-05-23T16:32:36+0200 [Controller  24588] Using default node shutdown triggers ['shutdown_on_worker_exit']
2019-05-23T16:32:36+0200 [Controller  24588] Booting node <crossbar.node.node.Node.boot>
2019-05-23T16:32:36+0200 [Controller  24588] Booting node from local configuration [parallel_worker_start=False] .. <crossbar.node.node.Node.boot_from_config>
2019-05-23T16:32:36+0200 [Controller  24588] Will start 1 worker ..
2019-05-23T16:32:36+0200 [Controller  24588] Order node to start Router worker001
2019-05-23T16:32:36+0200 [Controller  24588] Starting router worker worker001 <crossbar.node.controller.NodeController.start_worker>

2019-05-23T16:32:39+0200 [Router      24600] Starting worker "worker001" for node "a2denedis" on realm "crossbar" with personality "standalone" <crossbar.worker.router.RouterController>
2019-05-23T16:32:39+0200 [Router      24600] Running as PID 24600 on CPython-EPollReactor
2019-05-23T16:32:39+0200 [Router      24600] Entering event reactor ...
2019-05-23T16:32:39+0200 [Controller  24588] Router.attach(session=4139832490129409)
2019-05-23T16:32:39+0200 [Controller  24588] Router.attach(session=4139832490129409): attached session 4139832490129409 to router realm "crossbar"
2019-05-23T16:32:39+0200 [Router      24600] Router worker session for "worker001" joined realm "crossbar" on node router <crossbar.worker.router.RouterController.onJoin>
2019-05-23T16:32:39+0200 [Router      24600] Registered 41 procedures
2019-05-23T16:32:39+0200 [Router      24600] Router worker session for "worker001" ready
2019-05-23T16:32:39+0200 [Controller  24588] Ok, node has started Router worker001
2019-05-23T16:32:39+0200 [Controller  24588] Configuring Router worker001 ..
2019-05-23T16:32:39+0200 [Controller  24588] Order Router worker001 to start Realm realm001
2019-05-23T16:32:39+0200 [Router      24600] Starting router realm realm001 <crossbar.worker.router.RouterController.start_router_realm>
2019-05-23T16:32:39+0200 [Router      24600] RouterFactory.start_realm: router created for realm "realm1"
2019-05-23T16:32:39+0200 [Router      24600] Router.attach(session=710565983507658)
2019-05-23T16:32:39+0200 [Router      24600] Router.attach(session=710565983507658): attached session 710565983507658 to router realm "realm1"
2019-05-23T16:32:39+0200 [Router      24600] RouterServiceAgent: realm service session attached (details=SessionDetails(realm=<realm1>, session=710565983507658, authid=<None>, authrole=<trusted>, authmethod=None, authprovider=None, authextra=None, resumed=None, resumable=None, resume_token=None))
2019-05-23T16:32:39+0200 [Router      24600] RouterServiceAgent: realm service session ready (realm_name="realm1", on_ready=<Deferred at 0x7faaf5c3c8>)
2019-05-23T16:32:39+0200 [Router      24600] RouterServiceAgent started on realm "realm1"
2019-05-23T16:32:39+0200 [Router      24600] Realm "realm001" (name="realm1") started
2019-05-23T16:32:39+0200 [Controller  24588] Ok, Router worker001 has started Realm realm001
2019-05-23T16:32:39+0200 [Controller  24588] Order Realm realm001 to start Role role001
2019-05-23T16:32:39+0200 [Router      24600] Starting role "role001" on realm "realm001" <crossbar.worker.router.RouterController.start_router_realm_role>
2019-05-23T16:32:39+0200 [Router      24600] role role001 on realm realm001 started
2019-05-23T16:32:39+0200 [Controller  24588] Ok, Realm realm001 has started Role role001
2019-05-23T16:32:39+0200 [Controller  24588] Order Router worker001 to start Transport transport001
2019-05-23T16:32:39+0200 [Router      24600] Starting router transport "transport001" <crossbar.worker.router.RouterController.start_router_transport>
2019-05-23T16:32:39+0200 [Router      24600] Creating router transport for "transport001" <crossbar.worker.transport.create_router_transport>
2019-05-23T16:32:39+0200 [Router      24600] Router transport created for "transport001" <crossbar.worker.transport.RouterWebTransport>
2019-05-23T16:32:39+0200 [Router      24600] Created "static" Web service on root path "/" of Web transport "transport001"
2019-05-23T16:32:39+0200 [Router      24600] Site starting on 8080
2019-05-23T16:32:39+0200 [Controller  24588] Ok, Router worker001 has started Transport transport001
2019-05-23T16:32:39+0200 [Controller  24588] Order Transport transport001 to start Web Service webservice001
2019-05-23T16:32:39+0200 [Router      24600] Starting "publisher" Web service on path "publish" of transport "transport001" <crossbar.worker.router.RouterController.start_web_transport_service>
2019-05-23T16:32:39+0200 [Router      24600] RouterController.onUserError(): "TypeError: add() missing 1 required positional argument: 'router'"
Traceback (most recent call last):
  File "/applications/enedis/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/applications/enedis/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
  File "/applications/enedis/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/applications/enedis/lib/python3.6/site-packages/crossbar/worker/router.py", line 844, in start_web_transport_service
    webservice = yield maybeDeferred(webservice_factory.create, transport, path, config)
--- <exception caught here> ---
  File "/applications/enedis/lib/python3.6/site-packages/crossbar/worker/router.py", line 844, in start_web_transport_service
    webservice = yield maybeDeferred(webservice_factory.create, transport, path, config)
  File "/applications/enedis/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/applications/enedis/lib/python3.6/site-packages/crossbar/webservice/rest.py", line 59, in create
    authrole=config.get('role', 'anonymous'))
builtins.TypeError: add() missing 1 required positional argument: 'router'

2019-05-23T16:32:39+0200 [Controller  24588] Could not start node: Traceback (most recent call last):
--- <exception caught here> ---
  File "/applications/enedis/lib/python3.6/site-packages/crossbar/node/node.py", line 375, in start
    yield self.personality.Node.boot(self)
  File "/applications/enedis/lib/python3.6/site-packages/crossbar/node/node.py", line 498, in boot_from_config
    yield d
  File "/applications/enedis/lib/python3.6/site-packages/crossbar/node/node.py", line 475, in configure_worker
    yield config_fn(worker_logname, worker_id, worker)
  File "/applications/enedis/lib/python3.6/site-packages/crossbar/node/node.py", line 661, in _configure_native_worker_router
    options=CallOptions())
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<wamp.error.runtime_error>, args=["add() missing 1 required positional argument: 'router'"], kwargs={}, enc_algo=None, callee=None, callee_authid=None, callee_authrole=None, forward_for=None)

2019-05-23T16:32:39+0200 [Controller  24588] sending TERM to subprocess 24600
2019-05-23T16:32:39+0200 [Controller  24588] waiting for 24600 to exit...
2019-05-23T16:32:39+0200 [Router      24600] Native worker received SIGTERM - shutting down ..
2019-05-23T16:32:39+0200 [Router      24600] Shutdown of worker requested!
2019-05-23T16:32:39+0200 [Controller  24588] Router.detach(session=4139832490129409)
2019-05-23T16:32:39+0200 [Controller  24588] Router.detach(session=4139832490129409): detached sessions [4139832490129409] from router realm "crossbar"
2019-05-23T16:32:39+0200 [Router      24600] Connection to node controller closed cleanly
2019-05-23T16:32:39+0200 [Router      24600] (TCP Port 8080 Closed)
2019-05-23T16:32:39+0200 [Controller  24588] Native worker connection closed cleanly.
2019-05-23T16:32:39+0200 [Controller  24588] Node worker worker001 ended successfully
2019-05-23T16:32:39+0200 [Controller  24588] Checking for node shutdown: worker_exit_success=True, shutdown_requested=False, node_shutdown_triggers=['shutdown_on_worker_exit']
2019-05-23T16:32:39+0200 [Controller  24588] Node worker ended, and trigger 'shutdown_on_worker_exit' is active: will shutdown node ..
2019-05-23T16:32:39+0200 [Controller  24588] Node shutdown requested (restart=False, mode=None, reactor.running=True) ..
```

#### Configuration

pip --version
```
pip 19.1.1 from /applications/enedis/lib/python3.6/site-packages/pip (python 3.6)
```

pip freeze
```
amqp==2.4.2
argh==0.26.2
argon2-cffi==19.1.0
asn1crypto==0.24.0
attrs==19.1.0
autobahn==19.5.1
Automat==0.7.0
bcrypt==3.1.6
billiard==3.6.0.0
bitstring==3.1.5
cbor==1.0.0
cbor2==4.1.2
celery==4.3.0
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
Click==7.0
constantly==15.1.0
crossbar==19.5.1
crossbarhttp3==1.1
cryptography==2.6.1
Django==2.2.1
djangorestframework==3.9.4
flatbuffers==1.11
future==0.17.1
gobject==0.1.0
h2==3.1.0
hpack==3.0.0
hyperframe==5.2.0
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
Jinja2==2.10.1
kombu==4.5.0
lmdb==0.94
lz4==2.1.6
MarkupSafe==1.1.1
mistune==0.8.4
msgpack==0.6.1
netaddr==0.7.19
numpy==1.15.4
passlib==1.7.1
pathtools==0.1.2
priority==1.3.0
protobuf==3.7.1
psutil==5.6.2
psycopg2==2.8.2
py-ubjson==0.13.0
pyasn1==0.4.5
pyasn1-modules==0.2.5
pycairo==1.18.1
pycparser==2.19
Pygments==2.4.0
PyGObject==3.32.1
PyHamcrest==1.9.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
PyQRCode==1.2.1
python-snappy==0.5.4
PyTrie==0.3.1
pytz==2019.1
pyudev==0.21.0
PyYAML==5.1
requests==2.21.0
sdnotify==0.3.2
service-identity==18.1.0
setproctitle==1.1.10
sh==1.12.14
six==1.12.0
sortedcontainers==2.1.0
sqlparse==0.3.0
treq==18.6.0
Twisted==19.2.0
txaio==18.8.1
txtorcon==19.0.0
u-msgpack-python==2.5.1
ujson==1.35
urllib3==1.24.3
vine==1.3.0
watchdog==0.9.0
zlmdb==19.4.1
zope.interface==4.6.0
```

Any idea is welcome

**Comment by vitimm144** [comment]
Hi, 

The same error happens here, but on crossbar 19.3.5 still works. Hope it helps.

Att, Victor.
