### ISSUE TITLE
Error in getting started example

### ISSUE THREAD

**Issue by meatballs** [crossbario/crossbar-examples#138]
Hi

I'm just starting to use crossbar for the first time and I've hit an error when attempting to follow the getting started guide.

I've cloned this repo and successfully started my router from within the getting started folder but, when I attempt to start the python publishing client, I get:

```
"ws://crossbar:8080/ws" "realm1"
Traceback (most recent call last):
  File "/app/1.hello-world/client_component_publish.py", line 37, in <module>
    component = Component(transports=url, realm=realmv)
  File "/usr/local/lib/python3.7/site-packages/autobahn/wamp/component.py", line 512, in __init__
    _create_transport(idx, transport, self._check_native_endpoint)
  File "/usr/local/lib/python3.7/site-packages/autobahn/wamp/component.py", line 171, in _create_transport
    is_secure, host, port, resource, path, params = parse_ws_url(transport['url'])
  File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/util.py", line 140, in parse_url
    raise Exception("invalid WebSocket URL: protocol scheme '{}' is not for WebSocket".format(parsed.scheme))
Exception: invalid WebSocket URL: protocol scheme '' is not for WebSocket
```

**Comment by meatballs** [comment]
**Update**
I installed crossbar into a virtualenv and the example starts without error. This must be something specific to the docker image.
