### ISSUE TITLE
crossbar unable to start for the real time monitor using django

### ISSUE THREAD

**Issue by lebeier** [crossbario/crossbar-examples#16]
2015-05-13 11:56:06+0800 [Controller   5214] Crossbar.io 0.10.4 starting
2015-05-13 11:56:06+0800 [Controller   5214] Running on CPython using EPollReactor reactor
2015-05-13 11:56:06+0800 [Controller   5214] Starting from node directory /home/moxlotus/Documents/realtimemonitor/.crossbar
2015-05-13 11:56:06+0800 [Controller   5214] Starting from local configuration '/home/moxlotus/Documents/realtimemonitor/.crossbar/config.json'
2015-05-13 11:56:06+0800 [Controller   5214] Traceback (most recent call last):
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/bin/crossbar", line 9, in <module>
2015-05-13 11:56:06+0800 [Controller   5214]     load_entry_point('crossbar==0.10.4', 'console_scripts', 'crossbar')()
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/cli.py", line 665, in run
2015-05-13 11:56:06+0800 [Controller   5214]     options.func(options)
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/cli.py", line 404, in run_command_start
2015-05-13 11:56:06+0800 [Controller   5214]     node.start()
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/node.py", line 108, in start
2015-05-13 11:56:06+0800 [Controller   5214]     config = check_config_file(configfile, silence=True)
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/common/checkconfig.py", line 1876, in check_config_file
2015-05-13 11:56:06+0800 [Controller   5214]     check_config(config, silence)
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/common/checkconfig.py", line 1850, in check_config
2015-05-13 11:56:06+0800 [Controller   5214]     check_worker(worker, silence)
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/common/checkconfig.py", line 1754, in check_worker
2015-05-13 11:56:06+0800 [Controller   5214]     check_router(worker, silence)
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/common/checkconfig.py", line 1499, in check_router
2015-05-13 11:56:06+0800 [Controller   5214]     check_router_transport(transport, silence)
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/common/checkconfig.py", line 1253, in check_router_transport
2015-05-13 11:56:06+0800 [Controller   5214]     check_listening_transport_web(transport)
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/common/checkconfig.py", line 871, in check_listening_transport_web
2015-05-13 11:56:06+0800 [Controller   5214]     check_paths(paths)
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/common/checkconfig.py", line 926, in check_paths
2015-05-13 11:56:06+0800 [Controller   5214]     check_web_path_service(p, paths[p], nested)
2015-05-13 11:56:06+0800 [Controller   5214]   File "/usr/local/lib/python2.7/dist-packages/crossbar/common/checkconfig.py", line 822, in check_web_path_service
2015-05-13 11:56:06+0800 [Controller   5214]     raise Exception("invalid type '{}' for sub-path service in Web transport path service '{}' configuration\n\n{}".format(ptype, path, config))
2015-05-13 11:56:06+0800 [Controller   5214] Exception: invalid type 'pusher' for sub-path service in Web transport path service 'notify' configuration
2015-05-13 11:56:06+0800 [Controller   5214] 
2015-05-13 11:56:06+0800 [Controller   5214] {u'realm': u'realm1', u'role': u'anonymous', u'type': u'pusher'}

How can this be solved?

**Comment by oberstet** [comment]
`invalid type 'pusher' for sub-path service in Web transport path service 'notify' configuration`

Sorry, the type was renamed from "pusher" to "publisher". Please see here: http://crossbar.io/docs/HTTP-Bridge-Services-Publisher/

**Comment by FirefighterBlu3** [comment]
the Django example still uses "pusher" at https://crossbar.io/docs/Adding-Real-Time-to-Django-Applications/
