### ISSUE TITLE
authenticate/wampcradynamic/python doesn't work with python 3.4

### ISSUE THREAD

**Issue by KrYpTeD974** [crossbario/crossbar-examples#39]
Using crossbar 0.11.1, I tried the example : **authenticate/wampcradynamic/python**  with python 3.4.
Many exceptions are thrown in the crossbar console and the web client can't connect. 
on_challenge isn't even fired. 

Works fine on Python 2.7

Edit: it may be twisted that isn't compatible with Python 3. 
Is this possible to have an example working on python 3?

**Comment by goeddea** [comment]
Current state: works on Python 3 (3.5.1 tested). Closing.

**Comment by oberstet** [comment]
works for me:

``` console
(cpy351_4) oberstet@corei7ub1310:~/scm/crossbario/crossbarexamples/authentication/wampcra/dynamic/python$ crossbar start
2016-04-17T16:09:11+0200 [Controller   2397] New node key generated!
2016-04-17T16:09:11+0200 [Controller   2397]      __  __  __  __  __  __      __     __
2016-04-17T16:09:11+0200 [Controller   2397]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-04-17T16:09:11+0200 [Controller   2397]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-04-17T16:09:11+0200 [Controller   2397]                                         
2016-04-17T16:09:11+0200 [Controller   2397]     Crossbar.io Version: 0.13.2
2016-04-17T16:09:11+0200 [Controller   2397]     Node Public Key: 66e3e844e7d46e9fc922b8f3700aef9c6daee453c191ef8b40112899456a14bd
2016-04-17T16:09:11+0200 [Controller   2397] 
2016-04-17T16:09:11+0200 [Controller   2397] Running from node directory '/home/oberstet/scm/crossbario/crossbarexamples/authentication/wampcra/dynamic/python/.crossbar'
2016-04-17T16:09:11+0200 [Controller   2397] Controller process starting (CPython-EPollReactor) ..
2016-04-17T16:09:11+0200 [Controller   2397] Node configuration loaded from 'config.json'
2016-04-17T16:09:11+0200 [Controller   2397] Node ID 'corei7ub1310' set from hostname
2016-04-17T16:09:11+0200 [Controller   2397] Using default node shutdown triggers ['shutdown_on_worker_exit']
2016-04-17T16:09:11+0200 [Controller   2397] Joined realm 'crossbar' on node management router
2016-04-17T16:09:11+0200 [Controller   2397] Starting Router with ID 'worker-001'...
2016-04-17T16:09:11+0200 [Router       2401] Worker process starting (CPython-EPollReactor) ..
2016-04-17T16:09:11+0200 [Controller   2397] Router with ID 'worker-001' and PID 2401 started
2016-04-17T16:09:11+0200 [Router       2401] Realm 'realm1' started
2016-04-17T16:09:11+0200 [Controller   2397] Router 'worker-001': realm 'realm-001' (named 'realm1') started
2016-04-17T16:09:11+0200 [Controller   2397] Router 'worker-001': role 'role-001' (named 'authenticator') started on realm 'realm-001'
2016-04-17T16:09:11+0200 [Controller   2397] Router 'worker-001': role 'role-002' (named 'backend') started on realm 'realm-001'
2016-04-17T16:09:11+0200 [Controller   2397] Router 'worker-001': role 'role-003' (named 'frontend') started on realm 'realm-001'
2016-04-17T16:09:11+0200 [Router       2401] started component: authenticator.AuthenticatorSession id=8233040766520965
2016-04-17T16:09:11+0200 [Router       2401] WAMP-CRA dynamic authenticator registered!
2016-04-17T16:09:11+0200 [Controller   2397] Router 'worker-001': component 'component-001' started
2016-04-17T16:09:11+0200 [Router       2401] started component: backend.BackendSession id=5247362298141924
2016-04-17T16:09:11+0200 [Router       2401] Backend session joined: SessionDetails(realm=<realm1>, session=5247362298141924, authid=<None>, authrole=<backend>, authmethod=None, authprovider=None, authextra=None)
2016-04-17T16:09:11+0200 [Router       2401] ok, subscribed to topic com.example.topic1
2016-04-17T16:09:11+0200 [Router       2401] ok, subscribed to topic com.foobar.topic1
2016-04-17T16:09:11+0200 [Router       2401] ok, subscribed to topic com.foobar.topic2
2016-04-17T16:09:11+0200 [Router       2401] subscription failed (this is expected!) ApplicationError(error=<wamp.error.not_authorized>, args=["session is not authorized to subscribe to topic 'com.example.topic2'"], kwargs={}, enc_algo=None)
2016-04-17T16:09:11+0200 [Router       2401] procedure add2() registered
2016-04-17T16:09:11+0200 [Controller   2397] Router 'worker-001': component 'component-002' started
2016-04-17T16:09:11+0200 [Router       2401] Site starting on 8080
2016-04-17T16:09:11+0200 [Controller   2397] Router 'worker-001': transport 'transport-001' started
```

**Comment by goeddea** [comment]
... and then you start the Web client, and this happens (should have included this when re-opening):

```
2016-04-17T18:36:34+0200 [Router      11394] WAMP-CRA dynamic authenticator invoked: realm='realm1', authid='joe'
2016-04-17T18:36:34+0200 [Router      11394] {'authextra': None,
2016-04-17T18:36:34+0200 [Router      11394]  'authmethod': None,
2016-04-17T18:36:34+0200 [Router      11394]  'session': 3492437524193053,
2016-04-17T18:36:34+0200 [Router      11394]  'transport': {'cbtid': None,
2016-04-17T18:36:34+0200 [Router      11394]                'http_headers_received': {'accept-encoding': 'gzip, deflate, '
2016-04-17T18:36:34+0200 [Router      11394]                                                             'sdch',
2016-04-17T18:36:34+0200 [Router      11394]                                          'accept-language': 'en-US,en;q=0.8,de-DE;q=0.6,de;q=0.4',
2016-04-17T18:36:34+0200 [Router      11394]                                          'cache-control': 'no-cache',
2016-04-17T18:36:34+0200 [Router      11394]                                          'connection': 'Upgrade',
2016-04-17T18:36:34+0200 [Router      11394]                                          'cookie': '__wzd34ca58d53bda=1454858667; '
2016-04-17T18:36:34+0200 [Router      11394]                                                    'session=.eJw9zMsKgkAAQNFfiVm3GB8tFFxIphKjCylfm5iHxJii6MyYiv8eFbg_966AjgILToG9ggMBNkCzBYu8bEibKJTFimSaIlxbWOBDnEWSLpEo87tgerqwM3yj1hdF3ivS-gadTzXRoQO2Ixi5qB54qPB-puG1oXoq_ydL0sn5yYmzZyXk0OwShwmkXqfQcpnj2ZxQ7cro1pmR95qQwfoyYA1zv_X2AU-dP-0.CfUfPg.Eh_qE9HCGjd3xyVvikQOqP6uh3Y',
2016-04-17T18:36:34+0200 [Router      11394]                                          'dnt': '1',
2016-04-17T18:36:34+0200 [Router      11394]                                          'host': 'localhost:8080',
2016-04-17T18:36:34+0200 [Router      11394]                                          'origin': 'http://localhost:8080',
2016-04-17T18:36:34+0200 [Router      11394]                                          'pragma': 'no-cache',
2016-04-17T18:36:34+0200 [Router      11394]                                          'sec-websocket-extensions': 'permessage-deflate; '
2016-04-17T18:36:34+0200 [Router      11394]                                                                      'client_max_window_bits',
2016-04-17T18:36:34+0200 [Router      11394]                                          'sec-websocket-key': '82CvBmTRjA4tuucfO51qJQ==',
2016-04-17T18:36:34+0200 [Router      11394]                                          'sec-websocket-protocol': 'wamp.2.json',
2016-04-17T18:36:34+0200 [Router      11394]                                          'sec-websocket-version': '13',
2016-04-17T18:36:34+0200 [Router      11394]                                          'upgrade': 'websocket',
2016-04-17T18:36:34+0200 [Router      11394]                                          'user-agent': 'Mozilla/5.0 (X11; '
2016-04-17T18:36:34+0200 [Router      11394]                                                        'Linux x86_64) '
2016-04-17T18:36:34+0200 [Router      11394]                                                        'AppleWebKit/537.36 '
2016-04-17T18:36:34+0200 [Router      11394]                                                        '(KHTML, like Gecko) '
2016-04-17T18:36:34+0200 [Router      11394]                                                        'Chrome/49.0.2623.112 '
2016-04-17T18:36:34+0200 [Router      11394]                                                        'Safari/537.36'},
2016-04-17T18:36:34+0200 [Router      11394]                'http_headers_sent': {},
2016-04-17T18:36:34+0200 [Router      11394]                'peer': 'tcp4:127.0.0.1:59690',
2016-04-17T18:36:34+0200 [Router      11394]                'protocol': 'wamp.2.json',
2016-04-17T18:36:34+0200 [Router      11394]                'type': 'websocket'}}
2016-04-17T18:36:34+0200 [Router      11394] add2() called with 2 and 3
2016-04-17T18:36:34+0200 [Router      11394] Fatal error in component: While firing <function BackendSession.onJoin.<locals>.onhello at 0x7f660df6d1e0> subscribed under 7268093708185767. - onhello() missing 1 required positional argument: 'msg'
Traceback (most recent call last):
  File "/home/goeddea/venvs/cpy3_trunk/lib/python3.5/site-packages/crossbar-0.13.1-py3.5.egg/crossbar/router/router.py", line 159, in send
    session._transport.send(msg)
  File "/home/goeddea/venvs/cpy3_trunk/lib/python3.5/site-packages/crossbar-0.13.1-py3.5.egg/crossbar/router/session.py", line 228, in send
    self._session.onMessage(msg)
  File "/home/goeddea/venvs/cpy3_trunk/lib/python3.5/site-packages/autobahn/wamp/protocol.py", line 587, in onMessage
    future = txaio.as_future(handler.fn, *invoke_args, **invoke_kwargs)
  File "/home/goeddea/venvs/cpy3_trunk/lib/python3.5/site-packages/txaio/tx.py", line 407, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/goeddea/venvs/cpy3_trunk/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
builtins.TypeError: onhello() missing 1 required positional argument: 'msg'
```
