### ISSUE TITLE
RESTCallee isn't working

### ISSUE THREAD

**Issue by johnnywell** [crossbario/crossbar-examples#52]
I'm getting this response from the rest callee example.

``` json
{"args":["no callee registered for procedure 'com.myapp.rest'"],"error":"wamp.error.no_such_procedure"}
```

Something changed on Crossbar?

**Comment by goeddea** [comment]
What precisely are you doing to get this error? The example at least starts up fine.

**Comment by johnnywell** [comment]
I just ran crossbar then I made the example request:

``` json
curl -H "Content-Type: application/json" \
    -d '{"procedure": "com.myapp.rest", "kwargs": {"url": "get", "method": "GET"}}' \
    http://127.0.0.1:8080/call
```

**Comment by oberstet** [comment]
well, do you have a component that registered `com.myapp.rest`?

anyway, try the example without modification.

**Comment by johnnywell** [comment]
Yeah, I tried the example without modification, actually the only change was on pythonpath due the virtualenv.

**Comment by oberstet** [comment]
works for me (with current trunk of txaio, autobahn-python and crossbar):

``` console
oberstet@thinkpad-t430s:~/scm/crossbario/crossbarexamples/rest/callee$ cpy2_1 
(python279_1)oberstet@thinkpad-t430s:~/scm/crossbario/crossbarexamples/rest/callee$ curl -H "Content-Type: application/json" \
>     -d '{"procedure": "com.myapp.rest", "kwargs": {"url": "get", "method": "GET"}}' \
>     http://127.0.0.1:8080/call
{"args":[{"content":"{\n  \"args\": {}, \n  \"headers\": {\n    \"Accept-Encoding\": \"gzip\", \n    \"Host\": \"httpbin.org\"\n  }, \n  \"origin\": \"88.217.4.59\", \n  \"url\": \"https://httpbin.org/get\"\n}\n","headers":{"Content-Encoding":[""],"Server":["nginx"],"Access-Control-Allow-Credentials":["true"],"Date":["Wed, 02 Dec 2015 12:33:31 GMT"],"Access-Control-Allow-Origin":["*"],"Content-Type":["application/json"]},"code":200}]}(python279_1)oberstet@thinkpad-t430s:~/scm/crossbario/crossbarexamples/rest/callee$ 
```

and

``` console
(python279_1)oberstet@thinkpad-t430s:~/scm/crossbario/crossbarexamples/rest/callee$ crossbar start
2015-12-02T13:33:02+0100 [Controller  24125]      __  __  __  __  __  __      __     __
2015-12-02T13:33:02+0100 [Controller  24125]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2015-12-02T13:33:02+0100 [Controller  24125]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2015-12-02T13:33:02+0100 [Controller  24125]                                         
2015-12-02T13:33:02+0100 [Controller  24125]     Version: 0.11.2     
2015-12-02T13:33:02+0100 [Controller  24125] 
2015-12-02T13:33:02+0100 [Controller  24125] Starting from node directory /home/oberstet/scm/crossbario/crossbarexamples/rest/callee/.crossbar
2015-12-02T13:33:02+0100 [Controller  24125] Loading node configuration file '/home/oberstet/scm/crossbario/crossbarexamples/rest/callee/.crossbar/config.json'
2015-12-02T13:33:02+0100 [Controller  24125] Entering reactor event loop...
2015-12-02T13:33:02+0100 [Controller  24125] Joined realm 'crossbar' on node management router
2015-12-02T13:33:02+0100 [Controller  24125] No WAMPlets detected in enviroment.
2015-12-02T13:33:02+0100 [Controller  24125] Starting Router with ID 'worker1'...
2015-12-02T13:33:02+0100 [Router      24130] Worker running under CPython-EPollReactor
2015-12-02T13:33:03+0100 [Controller  24125] Router with ID 'worker1' and PID 24130 started
2015-12-02T13:33:03+0100 [Controller  24125] Router 'worker1': realm 'realm1' (named 'realm1') started
2015-12-02T13:33:03+0100 [Controller  24125] Router 'worker1': role 'role1' (named 'anonymous') started on realm 'realm1'
2015-12-02T13:33:03+0100 [Router      24130] Site starting on 8080
2015-12-02T13:33:03+0100 [Controller  24125] Router 'worker1': transport 'transport1' started
2015-12-02T13:33:03+0100 [Controller  24125] Starting Container with ID 'worker2'...
2015-12-02T13:33:03+0100 [Container   24135] Worker running under CPython-EPollReactor
2015-12-02T13:33:03+0100 [Controller  24125] Container with ID 'worker2' and PID 24135 started
2015-12-02T13:33:03+0100 [Controller  24125] Container 'worker2': component 'component1' started
2015-12-02T13:33:30+0100 [Container   24135] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f6bc3f30440>
2015-12-02T13:34:36+0100 [Container   24135] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f6bc3f30440>
```

**Comment by oberstet** [comment]
there seems to be an issue on Python 3.5 though:

``` console
(python350_1)oberstet@thinkpad-t430s:~/scm/crossbario/crossbarexamples/rest/callee$ crossbar version
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 0.11.2
   Autobahn         : 0.11.0
     UTF8 Validator : wsaccel-0.6.2
     XOR Masker     : wsaccel-0.6.2
     JSON Codec     : ujson-1.34
     MsgPack Codec  : msgpack-python-0.4.6
   Twisted          : 15.5.0-EPollReactor
   Python           : 3.5.0/CPython
 OS                 : Linux-3.13.0-68-generic-x86_64-with-debian-jessie-sid
 Machine            : x86_64

(python350_1)oberstet@thinkpad-t430s:~/scm/crossbario/crossbarexamples/rest/callee$ crossbar start
2015-12-02T13:40:34+0100 [Controller  24781]      __  __  __  __  __  __      __     __
2015-12-02T13:40:34+0100 [Controller  24781]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2015-12-02T13:40:34+0100 [Controller  24781]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2015-12-02T13:40:34+0100 [Controller  24781]                                         
2015-12-02T13:40:34+0100 [Controller  24781]     Version: 0.11.2     
2015-12-02T13:40:34+0100 [Controller  24781] 
2015-12-02T13:40:34+0100 [Controller  24781] Starting from node directory /home/oberstet/scm/crossbario/crossbarexamples/rest/callee/.crossbar
2015-12-02T13:40:34+0100 [Controller  24781] Loading node configuration file '/home/oberstet/scm/crossbario/crossbarexamples/rest/callee/.crossbar/config.json'
2015-12-02T13:40:34+0100 [Controller  24781] Entering reactor event loop...
2015-12-02T13:40:34+0100 [Controller  24781] Warning, could not set process title (setproctitle not installed)
2015-12-02T13:40:34+0100 [Controller  24781] Joined realm 'crossbar' on node management router
2015-12-02T13:40:34+0100 [Controller  24781] No WAMPlets detected in enviroment.
2015-12-02T13:40:34+0100 [Controller  24781] Starting Router with ID 'worker1'...
2015-12-02T13:40:34+0100 [Router      24785] Worker running under CPython-EPollReactor
2015-12-02T13:40:35+0100 [Controller  24781] Router with ID 'worker1' and PID 24785 started
2015-12-02T13:40:35+0100 [Controller  24781] Router 'worker1': realm 'realm1' (named 'realm1') started
2015-12-02T13:40:35+0100 [Controller  24781] Router 'worker1': role 'role1' (named 'anonymous') started on realm 'realm1'
2015-12-02T13:40:35+0100 [Router      24785] Site starting on 8080
2015-12-02T13:40:35+0100 [Controller  24781] Router 'worker1': transport 'transport1' started
2015-12-02T13:40:35+0100 [Controller  24781] Starting Container with ID 'worker2'...
2015-12-02T13:40:35+0100 [Container   24789] Worker running under CPython-EPollReactor
2015-12-02T13:40:35+0100 [Controller  24781] Container with ID 'worker2' and PID 24789 started
2015-12-02T13:40:35+0100 [Container   24789] Component loading failed:

Failed to import class 'crossbar.adapter.rest.RESTCallee'
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/txaio/txaio/tx.py", line 338, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "/home/oberstet/python350_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/container.py", line 191, in start_container_component
    create_component = _appsession_loader(config)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/__init__.py", line 68, in _appsession_loader
    klassname, Failure(e).getTraceback())
--- <exception caught here> ---
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/__init__.py", line 59, in _appsession_loader
    component = getattr(module, klass_name)
builtins.AttributeError: module 'crossbar.adapter.rest' has no attribute 'RESTCallee'

2015-12-02T13:40:35+0100 [Container   24789] NativeWorkerSession.onUserError
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/websocket.py", line 170, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 590, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/home/oberstet/scm/crossbario/txaio/txaio/tx.py", line 338, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/oberstet/python350_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/container.py", line 191, in start_container_component
    create_component = _appsession_loader(config)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/__init__.py", line 74, in _appsession_loader
    pythonpath=sys.path
autobahn.wamp.exception.ApplicationError: ApplicationError('crossbar.error.class_import_failed', args = ('Failed to import class \'crossbar.adapter.rest.RESTCallee\'\nTraceback (most recent call last):\n  File "/home/oberstet/scm/crossbario/txaio/txaio/tx.py", line 338, in as_future\n    return maybeDeferred(fun, *args, **kwargs)\n  File "/home/oberstet/python350_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/container.py", line 191, in start_container_component\n    create_component = _appsession_loader(config)\n  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/__init__.py", line 68, in _appsession_loader\n    klassname, Failure(e).getTraceback())\n--- <exception caught here> ---\n  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/__init__.py", line 59, in _appsession_loader\n    component = getattr(module, klass_name)\nbuiltins.AttributeError: module \'crossbar.adapter.rest\' has no attribute \'RESTCallee\'\n',), kwargs = {'pythonpath': ['/home/oberstet/scm/crossbario/crossbarexamples/rest/callee', '/home/oberstet/scm/crossbario/crossbar/crossbar/worker', '/home/oberstet/python350_1/bin', '/home/oberstet/scm/crossbario/autobahn-python', '/home/oberstet/scm/crossbario/txaio', '/home/oberstet/scm/crossbario/crossbar', '/home/oberstet/python350_1/lib/python35.zip', '/home/oberstet/python350_1/lib/python3.5', '/home/oberstet/python350_1/lib/python3.5/plat-linux', '/home/oberstet/python350_1/lib/python3.5/lib-dynload', '/home/oberstet/python350/lib/python3.5', '/home/oberstet/python350/lib/python3.5/plat-linux', '/home/oberstet/python350_1/lib/python3.5/site-packages']})

2015-12-02T13:40:35+0100 [Controller  24781] crossbar.error.class_import_failed: Failed to import class 'crossbar.adapter.rest.RESTCallee'
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/txaio/txaio/tx.py", line 338, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "/home/oberstet/python350_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/container.py", line 191, in start_container_component
    create_component = _appsession_loader(config)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/__init__.py", line 68, in _appsession_loader
    klassname, Failure(e).getTraceback())
--- <exception caught here> ---
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/__init__.py", line 59, in _appsession_loader
    component = getattr(module, klass_name)
builtins.AttributeError: module 'crossbar.adapter.rest' has no attribute 'RESTCallee'

2015-12-02T13:40:35+0100 [Controller  24781] sending TERM to subprocess 24785
2015-12-02T13:40:35+0100 [Controller  24781] waiting for 24785 to exit...
2015-12-02T13:40:35+0100 [Controller  24781] sending TERM to subprocess 24789
2015-12-02T13:40:35+0100 [Controller  24781] waiting for 24789 to exit...
2015-12-02T13:40:35+0100 [Router      24785] Received SIGTERM, shutting down.
2015-12-02T13:40:35+0100 [Container   24789] Received SIGTERM, shutting down.
2015-12-02T13:40:35+0100 [Router      24785] Connection to node controller lost.
2015-12-02T13:40:35+0100 [Router      24785] No more controller connection; shutting down.
2015-12-02T13:40:35+0100 [Router      24785] (TCP Port 8080 Closed)
2015-12-02T13:40:35+0100 [Container   24789] Connection to node controller lost.
2015-12-02T13:40:35+0100 [Container   24789] No more controller connection; shutting down.
2015-12-02T13:40:35+0100 [Controller  24781] Process connection gone: A process has ended with a probable error condition: process ended with exit code 1.
2015-12-02T13:40:35+0100 [Controller  24781] Node worker worker1 ended (1 workers left)
2015-12-02T13:40:35+0100 [Controller  24781] Node shutting down ..
2015-12-02T13:40:35+0100 [Controller  24781] Shutting down node...
2015-12-02T13:40:35+0100 [Controller  24781] Process connection gone: A process has ended with a probable error condition: process ended with exit code 1.
2015-12-02T13:40:35+0100 [Controller  24781] Node worker worker2 ended (0 workers left)
(python350_1)oberstet@thinkpad-t430s:~/scm/crossbario/crossbarexamples/rest/callee$ 
```

**Comment by oberstet** [comment]
@meejah @hawkowl ^

**Comment by johnnywell** [comment]
As I can see the only difference is the crossbar version, I'm running 0.11.1 from pypi.
I've tried to install it directly on the system to be sure it wasn't a virtualenv/pythonpath issue, but this way the response seems worst.

``` json
{"args":["Connection refused"],"error":"wamp.error.runtime_error"}
```

And the following from crossbar stream:

```
2015-12-02T10:49:05-0200 [Controller  22431] Automatically choosing optimal Twisted reactor
2015-12-02T10:49:05-0200 [Controller  22431] Running on Linux and optimal reactor (epoll) was installed.
2015-12-02T10:49:05-0200 [Controller  22431]      __  __  __  __  __  __      __     __
2015-12-02T10:49:05-0200 [Controller  22431]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2015-12-02T10:49:05-0200 [Controller  22431]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2015-12-02T10:49:05-0200 [Controller  22431]                                         
2015-12-02T10:49:05-0200 [Controller  22431]     Version: 0.11.1     
2015-12-02T10:49:05-0200 [Controller  22431] 
2015-12-02T10:49:05-0200 [Controller  22431] Starting from node directory /mnt/sda3/johnny/Workspace/crossbarexamples/rest/callee/.crossbar
2015-12-02T10:49:05-0200 [Controller  22431] Loading node configuration file '/mnt/sda3/johnny/Workspace/crossbarexamples/rest/callee/.crossbar/config.json'
2015-12-02T10:49:05-0200 [Controller  22431] Entering reactor event loop...
2015-12-02T10:49:05-0200 [Controller  22431] Warning, could not set process title (setproctitle not installed)
2015-12-02T10:49:05-0200 [Controller  22431] Process utilities not available
2015-12-02T10:49:05-0200 [Controller  22431] Joined realm 'crossbar' on node management router
2015-12-02T10:49:05-0200 [Controller  22431] No WAMPlets detected in enviroment.
2015-12-02T10:49:05-0200 [Controller  22431] Starting Router with ID 'worker1'...
2015-12-02T10:49:06-0200 [Router      22436] Worker running under CPython-EPollReactor
2015-12-02T10:49:06-0200 [Router      22436] Process utilities not available
2015-12-02T10:49:06-0200 [Controller  22431] Router with ID 'worker1' and PID 22436 started
2015-12-02T10:49:06-0200 [Controller  22431] Router 'worker1': realm 'realm1' (named 'realm1') started
2015-12-02T10:49:06-0200 [Controller  22431] Router 'worker1': role 'role1' (named 'anonymous') started on realm 'realm1'
2015-12-02T10:49:06-0200 [Router      22436] Site starting on 8080
2015-12-02T10:49:06-0200 [Controller  22431] Router 'worker1': transport 'transport1' started
2015-12-02T10:49:06-0200 [Controller  22431] Starting Container with ID 'worker2'...
2015-12-02T10:49:06-0200 [Container   22441] Worker running under CPython-EPollReactor
2015-12-02T10:49:06-0200 [Container   22441] Process utilities not available
2015-12-02T10:49:06-0200 [Controller  22431] Container with ID 'worker2' and PID 22441 started
2015-12-02T10:49:06-0200 [Controller  22431] Container 'worker2': component 'component1' started
2015-12-02T10:49:09-0200 [Container   22441] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f10efd9b3b0>
2015-12-02T10:49:09-0200 [Container   22441] Unhandled Error
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.

2015-12-02T10:49:09-0200 [Container   22441] 'Connection refused'
2015-12-02T10:49:09-0200 [Container   22441] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f10efd9b3b0>
```

Some version details:

```
> $ crossbar version                                                                              ⬡ 4.2.1 [±master]
Automatically choosing optimal Twisted reactor
Running on Linux and optimal reactor (epoll) was installed.
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 0.11.1
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-python-0.4.4
   Twisted          : 15.5.0-EPollReactor
   Python           : 2.7.9/CPython
 OS                 : Linux-3.19.3-1~exp1-x86_64-Intel-R-_Core-TM-_i5-4440_CPU_@_3.10GHz-with-gentoo-2.2.0
 Machine            : x86_64
```

**Comment by hawkowl** [comment]
Yeah, this is because treq was not ported to Python 3, so it doesn't exist on Python 3.5. Treq just got ported (I need to do a release), so we can fix this.

**Comment by oberstet** [comment]
@hawkowl ah, right. @johnnywell could you try crossbar trunk?

**Comment by johnnywell** [comment]
@oberstet I've just tried it but I got the same behavior as my last comment. I also cloned the crossbarexamples again just to be sure it is exactly the same as the repository.

Following version details:

```
> $ crossbar version                                                                              ⬡ 4.2.1 [±master]
Automatically choosing optimal Twisted reactor
Running on Linux and optimal reactor (epoll) was installed.
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 0.11.2
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-python-0.4.4
   Twisted          : 15.5.0-EPollReactor
   Python           : 2.7.9/CPython
 OS                 : Linux-3.19.3-1~exp1-x86_64-Intel-R-_Core-TM-_i5-4440_CPU_@_3.10GHz-with-gentoo-2.2.0
 Machine            : x86_64
```

**Comment by johnnywell** [comment]
Still the same with autobahn 0.11.0

**Comment by oberstet** [comment]
@johnnywell well, I can't reproduce this

**Comment by johnnywell** [comment]
@oberstet Yeah, I'm going crazy with this. I'll give it some time, this might give me some luck.

**Comment by oberstet** [comment]
@johnnywell do you have any kind of "fancy" network setup? like you are sitting behind a Web proxy or such for outgoing HTTP connections or are on a mobile or enterprise network?

**Comment by johnnywell** [comment]
@oberstet yes, I'm in a enterprise network behind a web proxy, besides that I have some "fancy" network setup for a Linux container on my machine. Don you think it can interfere running crossbar locally?

**Comment by oberstet** [comment]
yes, this (the web proxy) is likely the source of the issue. the REST callee essentially forwards a WAMP call into a HTTP request. and for the latter to cross the proxy, the REST bridge would need to know about that proxy. The REST bridge currently does not support that (I think .. @hawkowl )

**Comment by johnnywell** [comment]
Well, actually I'm already unsetting the proxy on the shell session where I'm making the calls. I can't even reach the crossbar rest caller if I don't do that.

**Comment by oberstet** [comment]
@johnnywell yep, whenever HTTP is involved, the proxy needs to be configured or circumvented explicitly. But for HTTP requests that really are outgoing (to the internet), the latter would require to configured exceptions in proxy for the target HTTP host. Unlikely on an enterprise network. 

anyway: https://github.com/crossbario/crossbar/issues/536

**Comment by johnnywell** [comment]
Turns out that was a proxy problem after all, but not between the caller and the callee. The error occurs because the RESTCallee wasn't able to call https://httpbin.org/, whit my internal REST API it works greatly.
