### ISSUE TITLE
unicode URIs Django Realtime Monitoring example

### ISSUE THREAD

**Issue by daninarv** [crossbario/crossbar-examples#58]
When I execute the client.py in django realtime monitoring example with python 2.7 I have the next error:

Traceback (most recent call last):
  File "client.py", line 139, in <module>
    app.run(url="ws://%s:8000/ws" % SERVER, debug=False, debug_wamp=False)
  File "C:\Users\Daniel\PythonProjects\DjangoCrossbar\env\lib\site-packages\autobahn\twisted\wamp.py", line 394, in run
    debug=debug, debug_wamp=debug_wamp, debug_app=debug_app)
  File "C:\Users\Daniel\PythonProjects\DjangoCrossbar\env\lib\site-packages\autobahn\twisted\wamp.py", line 133, in **init**
    assert(type(url) == six.text_type)
AssertionError

I saw a similar issue in "Fix demos for unicode URIs on 10 Sep 2014" but I don't know if it is the same.

**Comment by oberstet** [comment]
try: `app.run(url=u"ws://%s:8000/ws" % SERVER, debug=False, debug_wamp=False)`

Note the single added `u` character

**Comment by daninarv** [comment]
It works. Thanks!
